### PR TITLE
java: Enhance concurrency by tracking global refs per solver instance

### LINKED ISSUE #10256: (Java API) CVC5 crashes when using multiple solver instances in parallel
Hello,
I'm working on the JavaSMT project which uses CVC5 as one of its back-ends. Recently we noticed some crashes when CVC5 is used in parallel by several different threads, each running its own solver instance. I was able to boil the problem down to [this](https://github.com/daniel-raffler/cvc5/commit/983fe528f1f05c686e7bc246e84a443f5ea6bbd0) test case.  Here CVC5 crashes with the following stack trace:
```Stack: [0x00007fa691dfe000,0x00007fa691efe000],  sp=0x00007fa691efc820,  free space=1018k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libcvc5jni.so+0x4c983]  std::_Rb_tree_iterator<std::pair<long const, std::vector<_jobject*, std::allocator<_jobject*> > > > std::_Rb_tree<long, std::pair<long const, std::vector<_jobject*, std::allocator<_jobject*> > >, std::_Select1st<std::pair<long const, std::vector<_jobject*, std::allocator<_jobject*> > > >, std::less<long>, std::allocator<std::pair<long const, std::vector<_jobject*, std::allocator<_jobject*> > > > >::_M_emplace_hint_unique<std::piecewise_construct_t const&, std::tuple<long const&>, std::tuple<> >(std::_Rb_tree_const_iterator<std::pair<long const, std::vector<_jobject*, std::allocator<_jobject*> > > >, std::piecewise_construct_t const&, std::tuple<long const&>&&, std::tuple<>&&) [clone .isra.0]+0x163
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  io.github.cvc5.Solver.deletePointer(J)V+0
j  io.github.cvc5.AbstractPointer.deletePointer()V+14
j  io.github.cvc5.Solver.deletePointer()V+1
j  tests.JavaSmtBug437$Task.run()V+48
v  ~StubRoutines::call_stub 0x00007fa6f8137cc6
```
I did try translating the test to C++ [here](https://github.com/daniel-raffler/cvc5/commit/8701a55e710975ca530d9b4994340a67b6b65fc5), however, this version seems to be working fine. Both test cases are nearly identical and I was eventually able to find the issue in the JNI bindings. The problem here is that Solver.deletePointer() may be called on multiple Solver instances at the same time, however, the underlying "globalReference" map is not thread-safe. You can find a quick patches for the issue [here](https://github.com/daniel-raffler/cvc5/commit/ee6fab594c6d5eb04351af1a73b1d16718b65554).

Could something like this be included in a future version of CVC5?

Thanks,
Daniel

### PR DESCRIPTION
**Pull request by daniel-larraz**
This fixes #10256 by enabling different threads to concurrently run and free the memory of their own solver instances.

### CODE REVIEW

File: src/api/java/jni/api_solver.h [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+ *
+ * The cvc5 Java API.
+ */
+
+#ifndef CVC5__API_SOLVER_H
+#define CVC5__API_SOLVER_H
+#include <cvc5/cvc5.h>
+#include <jni.h>
+
+class ApiSolver : public cvc5::Solver
```
Comment (mudathirmahgoub) [inline src/api/java/jni/api_solver.h:21]: Nice, I like this idea of inheriting from public Solver. Perhaps we can apply this to Oracle and Plugin.

Comment (daniel-larraz) [reply src/api/java/jni/api_solver.h:21]: The application of this idea to `IOracle` and `AbstractPlugin` is not straightforward. `IOracle` is an interface, not a class. `AbstractPlugin`, on the other hand, is a class, so it could store a pointer. However, this would be a breaking change. `AbstractPlugin` is designed to be extended by users, so adding a new field could conflict with user-defined fields. I would postpone this change for now.

File: src/api/java/jni/api_solver.h [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+  /**
+   * Construct an ApiSolver.
+   */
+  ApiSolver(cvc5::TermManager& tm);
+
+  /**
+   * Create a new global reference to the object referred to by the obj
+   * argument, and store the object to be disposed of later.
+   */
+  jobject addGlobalReference(JNIEnv* env, jobject object);
```
Comment (mudathirmahgoub) [inline src/api/java/jni/api_solver.h:33]: Perhaps we can add here which kinds of global references needed to be stored globally.
Currently, Oracles and plugins.
