### PR TITLE
[IntToBV] Add check for unsupported operators

### LINKED ISSUE #8935: Segfault solve-int-as-bv on String formula
9480126b2c
```
$cvc5 -q bug.smt2
cvc5 suffered a segfault.
Offending address is 0x100000001
[1]    1614865 segmentation fault  cvc5 -q bug.smt2
$cat bug.smt2 
(set-option :solve-int-as-bv 1)
(declare-fun a () String)
(assert (ite (= (- 1) (str.to_int a)) false true))
(check-sat)
```

### PR DESCRIPTION
**Pull request by 4tXJ7f**
Fixes #8935. This adds a check for unsupported operators in the IntToBV
preprocessing pass and improves error messages. Previously, operators
such as `str.to_int`, which return an integer but do not take an integer
as an argument were not detected as unsupported.

### CODE REVIEW

File: src/preprocessing/passes/int_to_bv.cpp [hunk 1]
```diff
@@ -137,6 +138,7 @@ Node IntToBV::intToBV(TNode n, NodeMap& cache)
         if (type.isBitVector())
         {
           uint32_t bvsize = type.getBitVectorSize();
+          // max = std::max(bvsize, max);
```
Comment (ajreynol) [inline src/preprocessing/passes/int_to_bv.cpp:141]: Remove?

Comment (4tXJ7f) [reply src/preprocessing/passes/int_to_bv.cpp]: Oops, done.

**Review by ajreynol — APPROVED** [review]
