### PR TITLE
Fix reduction for seq.nth for strings

### LINKED ISSUE #8918: (--no-strings-lazy-pp) solution unsoundness on a string formula
OS: Ubuntu 18.04
Commit: https://github.com/cvc5/cvc5/commit/61026f8e494a460906fd6d37dc0766608cce7aee

```
[557] % cvc5 -q --strings-exp small.smt2
unsat
[558] % cvc5 -q --strings-exp --no-strings-lazy-pp small.smt2
sat
[559] % cvc5 -q --strings-exp --no-strings-lazy-pp --check-models small.smt2
Fatal failure within void cvc5::internal::smt::CheckModels::checkModel(cvc5::internal::theory::TheoryModel*, const cvc5::context::CDList<cvc5::internal::NodeTemplate<true> >&, bool) at /local/suz-local/software/CVC4/src/smt/check_models.cpp:134
Internal error detected SolverEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     (let ((_let_1 (str.at a 2))) (<= (str.to_int (str.++ "0" (str.from_int (ite (str.prefixof "-" _let_1) 0 (str.to_int _let_1))))) (- 1)))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
Aborted
[560] % cat small.smt2
(declare-fun a () String)
(assert (<= (str.to_int (str.++ "0" (str.from_int (ite (str.prefixof "-" (str.at a 2)) 0 (str.to_int (str.at a 2)))))) (- 1)))
(check-sat)
```

### PR DESCRIPTION
**Pull request by ajreynol**
Fixes #8918.

### CODE REVIEW

File: src/theory/strings/theory_strings_preprocess.cpp [hunk 1]
```diff
@@ -514,7 +516,16 @@ Node StringsPreprocess::reduce(Node t,
     Node b12 = nm->mkNode(STRING_LENGTH, sk1).eqNode(n);
     Node lsk2 = nm->mkNode(STRING_LENGTH, sk2);
     Node b13 = nm->mkNode(EQUAL, lsk2, nm->mkNode(SUB, lt0, t12));
-    Node b1 = nm->mkNode(AND, b11, b12, b13);
+    std::vector<Node> bchildren;
+    bchildren.push_back(b11);
+    bchildren.push_back(b12);
+    bchildren.push_back(b13);
```
Comment (4tXJ7f) [inline src/theory/strings/theory_strings_preprocess.cpp:522]:
```suggestion
    std::vector<Node> bchildren { b11, b12, b13 };
```

**Review by 4tXJ7f — APPROVED** [review]
LGTM, just a minor suggestion to avoid unnecessary function calls.
