### PR TITLE
ff: fix bitsum rewriter

### LINKED ISSUE #11969: Invalid model on Finite Field
Hi,
For the following instance, cvc5 https://github.com/cvc5/cvc5/commit/befcee5dd12f2183b6a16a5b3d0b0d87fa2edd87 gives an invalid model.
```
$ cat small.smt2 
(declare-const v (_ FiniteField 3))
(assert (= v (ff.bitsum (ff.mul v v) (as ff-1 (_ FiniteField 3)))))
(check-sat)
$ cvc5 --check-models small.smt2 -q
Fatal failure within void cvc5::internal::smt::CheckModels::checkModel(cvc5::internal::theory::TheoryModel*, const cvc5::context::CDList<cvc5::internal::NodeTemplate<true> >&, bool) at /home/cvc5/src/smt/check_models.cpp:207
Internal error detected SolverEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL { THEORY_FF }:
assertion:     (= v (ff.bitsum (ff.mul v v) #f2m3))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by alex-ozdemir**
It was multiplying each term t_i by 1 instead of 2^i.

Credits to Merlin Sun for finding the problem. This bug was introduced by me in my last patch when I implemented the rewriter for ff.bitsum.

fixes #11969

### CODE REVIEW

File: src/theory/ff/theory_ff_rewriter.cpp [hunk 1]
```diff
@@ -198,7 +198,7 @@ Node TheoryFiniteFieldsRewriter::postRewriteFfBitsum(TNode t)
   {
     if (child.isConst())
     {
-      acc = acc + child.getConst<FiniteFieldValue>();
+      acc = acc + multiplier * child.getConst<FiniteFieldValue>();
```
Comment (alex-ozdemir) [inline src/theory/ff/theory_ff_rewriter.cpp:201]: This is the fix.

File: test/regress/cli/regress0/ff/issue11969.smt2 [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+; COMMAND-LINE: --ff-solver gb
+(set-logic QF_FF)
+(set-info :smt-lib-version 2.6)
+(set-info :category "crafted")
+(declare-const v (_ FiniteField 3))
+; v = v^2 + 2*(-1)
+(assert (= v (ff.bitsum (ff.mul v v) (as ff-1 (_ FiniteField 3)))))
+; 0 = v^2 - v - 2 = (v + 1)(v - 2)
+; models are 1 and 2
+(check-sat)
```
Comment (alex-ozdemir) [inline test/regress/cli/regress0/ff/issue11969.smt2:14]: Merlin's test

File: test/regress/cli/regress0/ff/bitsum_eval.smt2 [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+(set-info :smt-lib-version 2.6)
+(set-info :category "crafted")
+(assert (= (ff.bitsum #f0m3 #f0m3 #f0m3) #f0m3))
+(assert (= (ff.bitsum #f1m3 #f0m3 #f0m3) #f1m3))
+(assert (= (ff.bitsum #f0m3 #f1m3 #f0m3) #f2m3))
+(assert (= (ff.bitsum #f0m3 #f0m3 #f1m3) #f1m3))
+(assert (= (ff.bitsum #f0m3 #f1m3 #f1m3) #f0m3))
+(assert (= (ff.bitsum #f1m3 #f2m3 #f0m3) #f2m3))
+(check-sat)
+
```
Comment (alex-ozdemir) [inline test/regress/cli/regress0/ff/bitsum_eval.smt2:16]: These are some of my tests, just to check the rewriter.

**Review by alex-ozdemir — COMMENTED** [review]
Providing some context for @ajreynol

**Review by ajreynol — APPROVED** [review]
