### PR TITLE
[proofs] [alethe] Fixes issue where clausal reasoning would clash with introduced literals

### LINKED ISSUE #9531: Invalid Alethe proof
**Describe the bug**

On this example, cvc5 produces an incorrect Alethe proof:
```
(set-logic QF_UF)
(declare-const x2 Bool)
(declare-const x Bool)
(declare-sort I 0)
(declare-fun u () I)
(declare-fun o (I I) I)
(declare-fun e () I)
(assert (or x x2))
(assert (or (= u (o u u)) (and (= u (o u u)) (or (not (= (o u (o u u)) (o (o (o e e) (o u (o u u))) (o e e)))) (= (o u (o u u)) (o (o e e) (o (o e e) (o u (o u u)))))))))
(assert (= (o e e) (o u u)))
(assert (or (= (o u (o u u)) (o (o e e) (o (o e e) (o u (o u u))))) (not (= (o u (o u u)) (o (o (o e e) (o u (o u u))) (o e e))))))
(assert (not (= (o u (o u u)) (o (o u u) (o (o e e) (o u (o u u)))))))
(check-sat)
```

This happens with commit 6a0abb70032db7bd747724477ca63372e7c801eb from main. 

To get the proof:
```
> cvc5 --dump-proofs --proof-format-mode=alethe --dag-thresh=0 --proof-granularity=theory-rewrite test.smt2
```
Then `carcara` complains:
```
> carcara check test.prf test.smt2
[ERROR] checking failed on step 't22' with rule 'resolution': pivot was not eliminated: '(not (= (o u (o u u)) (o (o (o e e) (o u (o u u))) (o e e))))'
invalid
```
Checking by hand confirms that carcara is right.

### PR DESCRIPTION
**Pull request by HanielB**
The fix is to do away with the clausal reasoning and prove the literal via rewriting.

Fixes #9531

### CODE REVIEW

File: src/proof/alethe/alethe_post_processor.cpp [hunk 1]
```diff
@@ -1826,6 +1826,68 @@ bool AletheProofPostprocessCallback::update(Node res,
...
+  CVC5_UNUSED AletheRule premiseChildPfRule =
+      getAletheRule(premisePf->getChildren()[0]->getArguments()[0]);
+  Assert((premisePfRule == AletheRule::CONTRACTION
+          || premisePfRule == AletheRule::REORDERING)
+         && premiseChildPfRule == AletheRule::OR);
+  // get great grand child
+  std::shared_ptr<ProofNode> premiseChildPf =
+      premisePf->getChildren()[0]->getChildren()[0];
+  Node premiseChildConclusion = premiseChildPf->getResult();
+  // Note that we need to add this proof node explicitly to cdp
```
Comment (Lachnitt) [inline src/proof/alethe/alethe_post_processor.cpp:1852]: explicitly (i.e., as an assume step)

File: src/proof/alethe/alethe_post_processor.cpp [hunk 2]
```diff
@@ -1826,6 +1826,68 @@ bool AletheProofPostprocessCallback::update(Node res,
   }
 }
 
+bool AletheProofPostprocessCallback::maybeReplacePremiseProof(Node premise,
```
Comment (Lachnitt) [inline src/proof/alethe/alethe_post_processor.cpp:1829]: It would be nice to have a comment with a proof tree here as it was done for the proof rules.

**Review by Lachnitt — APPROVED** [review]
LGTM, left some documentation comments that don't necessarily need to be addressed if not wanted.
