### PR TITLE
Use SAT context level for --bv-assert-input instead of decision level.

### LINKED ISSUE #6738: Incorrect answer with `--bv-assert-input`
Input:
```
(set-logic QF_BV)
(declare-fun N () Bool)                                          
(assert (not (= (_ bv1 1) (bvnot (ite N (_ bv1 1) (_ bv0 1)))))) 
(push)                                                           
(assert (not N))                                                 
(check-sat)                                                      
(pop)                                                            
(check-sat)                                                      
```

With `--incremental`:
```
unsat
sat
```

With `--incremental --bv-assert-input`:
```
unsat
unsat
```

### PR DESCRIPTION
**Pull request by mpreiner**
The decision level as previously implemented was not accurate since it
did not consider the user context level. This resulted in facts being
incorrectly recognized as input assertions, which happened for
incremental benchmarks.

Fixes #6738

Marking do-not-merge until cluster runs are done.

### CODE REVIEW

**Review by 4tXJ7f — APPROVED** [review]
LGTM, thanks for fixing this!

**Comment by mpreiner** [comment]
This option doesn't work anymore right now due to the initial push we do for `(reset-assertions)`. Checking for level = 1 doesn't work either since this will break `(reset-assertions)` in the BV solver (since assertions are not removed from the SAT solver).

File: src/prop/minisat/minisat.cpp [hunk 1]
```diff
@@ -258,9 +258,9 @@ bool MinisatSatSolver::isDecision(SatVariable decn) const {
   return d_minisat->isDecision( decn );
 }
 
-int32_t MinisatSatSolver::getDecisionLevel(SatVariable v) const
+int32_t MinisatSatSolver::getSatContextLevel(SatVariable v) const
```
Comment (ajreynol) [inline src/prop/minisat/minisat.cpp:261]: I'm wondering if there is a better name for this, since this seems like it could be confused with the level of the cvc5::SatContext.  Would `getContextLevel` be a better name?

**Review by 4tXJ7f — APPROVED** [review]
LGTM
