### PR TITLE
Fix pre vs. post-rewrite in proofs for theory preprocessor

### LINKED ISSUE #6754: (check-unsat-cores) Fatal failure at src/proof/conv_proof_generator.cpp:229
Commit: b8d09076
OS: Ubuntu 18.04

```
[552] % cvc4-1.8 -q --check-unsat-cores small.smt2
unsat
[553] % cvc5 -q --check-unsat-cores small.smt2
Fatal failure within virtual std::shared_ptr<cvc5::ProofNode> cvc5::TConvProofGenerator::getProofFor(cvc5::Node) at /local/suz-local/software/CVC4/src/proof/conv_proof_generator.cpp:229
Unhandled case encounteredTConvProofGenerator::getProofFor: TheoryPreprocessor::rtf (policy=FIXPOINT, cache policy=NEVER, term-context-sensitive): failed, mismatch (see -t tconv-pf-gen-debug for details)
                   source: (let ((_let_1 (ite a 0 1))) (and (>= (mod _let_1 2) 2) (>= _let_1 0) (not (>= _let_1 2))))
     requested conclusion: (and (>= (+ termITE_1 (* (- 2) linearIntDiv_2)) 2) (>= termITE_1 0) (not (>= termITE_1 2)))
conclusion from generator: (and (not (not (>= (+ termITE_1 (* (- 2) linearIntDiv_2)) 2))) (>= termITE_1 0) (not (>= termITE_1 2)))

Aborted
[554] % 
[554] % cat small.smt2
(declare-fun a () Bool)
(assert (> (mod (ite a 0 1) 2) 1))
(check-sat)
[555] % 
```

### PR DESCRIPTION
**Pull request by ajreynol**
This changes an annotation of a step of rewriting from "post" to "pre" in the theory preprocessor.
Fixes #6754.

### CODE REVIEW

File: src/theory/theory_preprocessor.cpp [hunk 1]
```diff
@@ -310,9 +310,10 @@ TrustNode TheoryPreprocessor::theoryPreprocess(
         rtfNode = ttfr.getNode();
         registerTrustedRewrite(ttfr, d_tpgRtf.get(), true);
       }
-      // Finish the conversion by rewriting. This is registered as a
-      // post-rewrite, since it is the last step applied for theory atoms.
-      Node retNode = rewriteWithProof(rtfNode, d_tpgRtf.get(), false);
+      // Finish the conversion by rewriting. Notice that we must consider this a
+      // pre-rewrite since we do not recursively register the rewriting steps
+      // of subterms of rtfNode.
```
Comment (HanielB) [inline src/theory/theory_preprocessor.cpp:315]: Could you say more about how this change solves the issue of not recursively registering the rewriting steps mentioned?

**Review by HanielB — APPROVED** [review]
LGTM
