### PR TITLE
Fixes for witness terms appearing in CEGQI instantiations

### LINKED ISSUE #8344: Fatal failure at src/theory/quantifiers/cegqi/ceg_instantiator.cpp:947
3c37d6aeb7

```
$cvc5 -q bug.smt2                                                                       
Fatal failure within bool cvc5::theory::quantifiers::CegInstantiator::constructInstantiationInc( 
cvc5::Node, cvc5::Node,  cvc5::theory::quantifiers::TermProperties&, cvc5::theory::quantifiers::
SolvedForm&, bool) at /bin/solvers/CVC4/src/theory/quantifiers/cegqi/ceg_instantiator.cpp:947
Check failure

 d_inelig.find(n) == d_inelig.end()

[1]    32428 abort      cvc5 -q bug.smt2
$cat bug.smt2 
(declare-fun a () String)
(assert (forall ((b Int)) (or (> (str.len a) b) (= 0 (mod b 74998)))))
(check-sat)
$
```

### PR DESCRIPTION
**Pull request by ajreynol**
Fixes #8344.

We now have cases where witness terms e.g. `(witness x : String. len(x) = N)` appear in model values.  These terms require special care in CEGQI.

There are 2 fixes in this PR:
(1) we update our policy on what a legal term is,
(2) we erase annotations from witness terms appearing in instantiations, which is required for ensuring that proofs are consistent.  Otherwise, the skolemization lemma for a witness term does not introduce the same skolem.

### CODE REVIEW

File: src/expr/annotation_elim_node_converter.h [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+
+#ifndef CVC4__PROOF__EXPR__ANNOTATION_ELIM_NODE_CONVERTER_H
+#define CVC4__PROOF__EXPR__ANNOTATION_ELIM_NODE_CONVERTER_H
+
+#include <iostream>
+#include <map>
+
+#include "expr/node.h"
+#include "expr/node_converter.h"
+#include "expr/type_node.h"
```
Comment (4tXJ7f) [inline src/expr/annotation_elim_node_converter.h:25]:
```suggestion
#include "expr/node.h"
#include "expr/node_converter.h"
```

**Review by 4tXJ7f — APPROVED** [review]
LGTM
