### PR TITLE
Fix placement of CVC5_EXPORT annotations

### LINKED ISSUE #10475: CVC5_EXPORT annotations are misplaced
### Discussed in https://github.com/cvc5/cvc5/discussions/10467

<div type='discussions-op-text'>

<sup>Originally posted by **rafaelsamenezes** March  6, 2024</sup>
Hello CVC5 team,

I have a CMake project and am trying to link using the prebuilt CVC5 from https://github.com/cvc5/cvc5/releases/tag/cvc5-1.1.2

However, it is failing with an error: `C:\Users\rafae\Downloads\cvc5-Win64-shared\cvc5-Win64-shared\include\cvc5/cvc5_kind.h(5634): error C2144: syntax error: 'int' should be preceded by ';'`. The line contains `[[deprecated("use std::to_string(Kind) instead.")]] std::string kindToString(Kind kind) CVC5_EXPORT;`

From my understanding the CVC5_EXPORT which adds ` __declspec(dllimport)`. I am not really familiar with using DLLs but [MSVC docs](https://learn.microsoft.com/en-us/cpp/cpp/declspec?view=msvc-170) states `The __declspec keywords should be placed at the beginning of a simple declaration. The compiler ignores, without warning, any __declspec keywords placed after * or & and in front of the variable identifier in a declaration.`

I also constructed a mini cmake project which replicates the issue that I am having

```
# CMakeLists.txt
cmake_minimum_required(VERSION 3.27)
project(cvc5_test)

set(CMAKE_CXX_STANDARD 17)

find_package(cvc5 REQUIRED
        HINTS ${CVC5_DIR}/lib/cmake ${CVC5_DIR}/lib64/cmake)

message(STATUS "CVC5 version: ${cvc5_VERSION}")

add_library(cvc5_test library.cpp)
target_link_libraries(cvc5_test cvc5::cvc5)
```

```
// library.cpp
#include <cvc5/cvc5.h>

void hello() {

}
```

Steps to run:

1. Download the prebuilt release of CVC5
2. Run cmake giving `-DCVC5_DIR=<path-to-prebuilt-release>`
3. Build

Do you have any advice on how to procede? 

</div>

### PR DESCRIPTION
**Pull request by daniel-larraz**
The CVC5_EXPORT macro uses the extended attribute syntax `__declspec(...)`. According to the MSVC doc:
> The __declspec keywords should be placed at the beginning of a simple declaration.

This PR fixes the CVC5_EXPORT annotations that were misplaced. Resolves #10475.

### CODE REVIEW

File: include/cvc5/cvc5.h [hunk 1]
```diff
@@ -1967,10 +1970,9 @@ std::ostream& operator<<(std::ostream& out,
  * @param unordered_map The map of terms to be serialized to the given stream.
  * @return The output stream.
  */
-template <typename V>
+template <typename V> CVC5_EXPORT
```
Comment (aniemetz) [inline include/cvc5/cvc5.h:1973]: Is this clang-formatted? Format differs from the changes right above.

Comment (daniel-larraz) [reply include/cvc5/cvc5.h]: It is not. Fixed.

**Review by aniemetz — APPROVED** [review]
