### PR TITLE
Fix regular expression aggressive elim

### LINKED ISSUE #6620: (re-elim, re-elim-agg) invalid model for string formula with regexes
Commit: https://github.com/cvc5/cvc5/commit/7440f0568b99842d87cb1f86eec21aed9f46b92a
OS: Ubuntu 18.04 

It appears to be a regression from cvc4-1.8. 

```
[515] % cvc4-1.8 -q --strings-exp --re-elim --re-elim-agg --check-models --dump-models small.smt2
sat
(model
(define-fun a () String "B")
(define-fun b () String "A")
)
[516] % cvc5 -q --strings-exp --re-elim --re-elim-agg --dump-models small.smt2
sat
(
(define-fun a () String "B")
(define-fun b () String "BA")
)
[517] % cvc5 -q --strings-exp --re-elim --re-elim-agg --check-models small.smt2
Fatal failure within void cvc5::smt::CheckModels::checkModel(cvc5::smt::Model*, cvc5::context::CDList<cvc5::NodeTemplate<true> >*, bool) at /local/suz-local/software/CVC4/src/smt/check_models.cpp:125
Internal error detectedSmtEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     (str.in_re (str.++ a "A") (re.* (re.++ (re.+ (str.to_re "B")) (str.to_re b))))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
Aborted
[518] % 
[518] % cat small.smt2
(declare-fun a () String)
(declare-fun b () String)
(assert (str.in_re (str.++ a "A") (re.* (re.++ (re.+ (str.to_re "B")) (str.to_re b)))))
(check-sat)
[519] % 
```

### LINKED ISSUE #6622: ( re-elim, re-elim-agg) refutation unsoundness on string formula with regexes
Commit: https://github.com/cvc5/cvc5/commit/a24d6c8cf774f971a3eff62f73b2558b01b04440
OS: Ubuntu 18.04
Possibly related: https://github.com/cvc5/cvc5/issues/6620

```
[591] % cvc4 -q --strings-exp small.smt2
sat
[592] % cvc4 -q --strings-exp --re-elim --re-elim-agg small.smt2
unsat
[593] % cat small.smt2
(declare-fun a () String)
(declare-fun b () String)
(assert (str.in_re (str.++ a b) (re.* (str.to_re "A"))))
(assert (str.in_re b (re.diff (re.union (str.to_re "A") (str.to_re "B")) (re.++ (str.to_re "A") (re.* (str.to_re "B")) (str.to_re "A")))))
(check-sat)
[594] % 
```

### PR DESCRIPTION
**Pull request by ajreynol**
Fixes #6620, fixes #6622.  Fixes https://github.com/cvc5/cvc5-projects/issues/254.

The benchmarks from the 2 issues timeout, a regression is added for the projects issue.

### CODE REVIEW

File: src/theory/strings/regexp_elim.cpp [hunk 1]
```diff
@@ -400,6 +400,12 @@ Node RegExpElimination::eliminateConcat(Node atom, bool isAgg)
       {
         sStartIndex = lens;
       }
+      else if (r==1 && sConstraints.size()==2)
```
Comment (4tXJ7f) [inline src/theory/strings/regexp_elim.cpp:403]: Apply ClangFormat.

**Review by 4tXJ7f — APPROVED** [review]
LGTM
