### PR TITLE
[proofs] [uf] Make EqProof conversion robust to fickle rewriting of n-ary kinds

### LINKED ISSUE #9205: Fatal failure when generating LFSC proof (ProofNodeManager::mkScope)
**Describe the bug**
Running `cvc5 --lang=smt2 --dump-proofs --proof-format=lfsc --proof-granularity=theory-rewrite` on 
[lfsc_proof2.txt](https://github.com/cvc5/cvc5/files/9727704/lfsc_proof2.txt) fails with this error:
```
unsat
Fatal failure within std::shared_ptr<cvc5::internal::ProofNode> cvc5::internal::ProofNodeManager::mkScope(std::shared_ptr<cvc5::internal::ProofNode>, std::vector<cvc5::internal::NodeTemplate<true> >&, bool, bool, cvc5::internal::Node) at /home/runner/work/cvc5/cvc5/src/proof/proof_node_manager.cpp:229
Unreachable code reached Generated a proof that is not closed by the scope: 
Free assumption: (= (bvadd (top.res.2.call_22_3 1) [...]
Use -t dump-proof-error for details on proof

Aborted (core dumped)
```
**Command line arguments**: --lang=smt2 --dump-proofs --proof-format=lfsc --proof-granularity=theory-rewrite
**cvc5 version/commit**: cvc5-Linux-2022-10-05-6b8341e
**Operating system**: Ubuntu 20.04

### PR DESCRIPTION
**Pull request by HanielB**
Since the equality engine reasons modulo AC for n-ary kinds, the EqProof conversion into ProofNode must account for this implicit reasoning. One of the things it relies on is that via rewriting it'll be able to convert an equality such as 
  `(= (f (f t1 t2 t3) t4) (f (f t5 t6) t7))`
into
  `(= (f t1 t2 t3 t4) (f t5 t6 t7))`

However whether the rewriter will always be able to do so depends on the theory: the strings one can, the BV one not.

This commit makes the conversion robust to this issue by testing whether the rewriter would get it and otherwise adding a TRUST_REWRITE step.

Fixes #9205

### CODE REVIEW

File: src/theory/uf/eq_proof.cpp [hunk 1]
```diff
@@ -1454,12 +1455,50 @@ Node EqProof::addToProof(CDProof* p,
...
+    //
+    //
+    //  If rewriting was able to do it, however, we just add the macro step.
+    if (res.isNull())
+    {
+      Trace("eqproof-conv")
+          << "EqProof::addToProof: adding a trust rewrite step\n";
+      Node bridgeEq = conclusion.eqNode(d_node);
+      p->addStep(bridgeEq,
+                 PfRule::TRUST_REWRITE,
```
Comment (ajreynol) [inline src/theory/uf/eq_proof.cpp:1486]: Can you use a new trusted PfRule for this?  Trusted proof rules should ideally be 1-to-1 from call sites in the code so that the source of these kinds of failures are easy to track.

**Review by ajreynol — CHANGES_REQUESTED** [review]

File: src/theory/uf/eq_proof.cpp (hunk 1 above)
Comment (HanielB) [reply src/theory/uf/eq_proof.cpp]: Sounds good. I've added one now.

**Review by ajreynol — APPROVED** [review]
