### PR TITLE
Check for higher-order variables in TheoryUF::ppRewrite

### LINKED ISSUE #7000: Assertion failure in theory_model_builder.cpp.
The following API call sequence fails with the assertion failure below:

```
Solver slv;                                                                   
Sort s1 = slv.getIntegerSort();                                               
Sort s2 = slv.mkFunctionSort(s1, s1);                                         
Sort s3 = slv.getRealSort();                                                  
Term t4 = slv.mkPi();                                                         
Term t7 = slv.mkConst(s3, "_x5");                                             
Term t37 = slv.mkConst(s2, "_x32");                                           
Term t59 = slv.mkConst(s2, "_x51");                                           
Term t72 = slv.mkTerm(EQUAL, t37, t59);                                       
Term t74 = slv.mkTerm(GT, t4, t7);                                            
slv.checkEntailed({t72, t74, t72, t72});    
```
```
Fatal failure within bool cvc5::theory::TheoryEngineModelBuilder::isAssignable(cvc5::TNode) at /cvc5/src/theory/theory_model_builder.cpp:158
Check failure

 !n.getType().isFunction()

Aborted (core dumped)
```

**cvc5 version/commit**: a796c4d8461f22aa523edd3031290e0ba03edd60

**`configure.sh` options**  
debug

### PR DESCRIPTION
**Pull request by ajreynol**
Fixes #7000.  That sequence of API calls now throws a logic exception.

### CODE REVIEW

File: src/theory/uf/ho_extension.cpp [hunk 1]
```diff
@@ -43,13 +43,16 @@ HoExtension::HoExtension(Env& env,
 Node HoExtension::ppRewrite(Node node)
 {
   // convert HO_APPLY to APPLY_UF if fully applied
-  if (node[0].getType().getNumChildren() == 2)
+  if (node.getKind()==HO_APPLY)
```
Comment (HanielB) [inline src/theory/uf/ho_extension.cpp:46]: clang-format
