### PR TITLE
Make CnfStream::toCNF iterative

### LINKED ISSUE #6111: Segmentation fault with large bit-width
**Describe the bug**
A sequence of API commands checking satisfiability with three assertions, one of which includes bit-vectors with a large bit-width results in a segmentation fault in both production and debug builds. I've attached a file with gdb output from the debug build: [gdb.txt](https://github.com/CVC4/CVC4/files/6119351/gdb.txt).

The cpp file to trigger this:
```
#include <iostream>
#include <vector>

#include "api/cvc4cpp.h"

using namespace CVC4::api;
using namespace std;


int main()
{
  Solver solver;
  solver.setLogic("QF_BV");
  Sort bvsort12979 = solver.mkBitVectorSort(12979);
  Term input2_1 = solver.mkConst(bvsort12979, "intpu2_1");
  Term zero = solver.mkBitVector(bvsort12979.getBVSize(), "0", 10);

  vector<Term> args1;
  args1.push_back(zero);
  args1.push_back(input2_1);
  Term bvult_res = solver.mkTerm(BITVECTOR_ULT, args1);
  solver.assertFormula(bvult_res);

  Sort bvsort4 = solver.mkBitVectorSort(4);
  Term concat_result_42 = solver.mkConst(bvsort4, "concat_result_42");
  Sort bvsort8 = solver.mkBitVectorSort(8);
  Term concat_result_43 = solver.mkConst(bvsort8, "concat_result_43");

  vector<Term> args2;
  args2.push_back(concat_result_42);
  args2.push_back(solver.mkTerm(solver.mkOp(BITVECTOR_EXTRACT, 7, 4), {concat_result_43}));
  solver.assertFormula(solver.mkTerm(EQUAL, args2));

  vector<Term> args3;
  args3.push_back(concat_result_42);
  args3.push_back(solver.mkTerm(solver.mkOp(BITVECTOR_EXTRACT, 3, 0), {concat_result_43}));
  solver.assertFormula(solver.mkTerm(EQUAL, args3));

  cout << solver.checkSat() << endl;

  return 0;
}
```

*Note*: This was found by running smt-switch with a CVC4 backend on the SMT-LIB non-incremental QF_BV benchmark `log-slicing/bvult_12979.smt2`. For some reason, the standalone CVC4 binary does not segfault on that file. However, I minimized with ddSMT running the smt-switch wrapper, then rewrote the file with CVC4 API commands (which does segfault).

**Command line arguments**: N/A
**CVC4 version/commit**: https://github.com/CVC4/CVC4/tree/a0dfbbbf3bcaf7a6edbe18e140b6d7b5c49c2f8d
**Operating system**: Ubuntu 18.04

**`configure.sh` options**
`debug`

**`configure.sh` output**
```
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building Debug build
-- Performing Test HAVE_FLAG_fno_inline
-- Performing Test HAVE_FLAG_fno_inline - Success
-- Configuring with C flag '-fno-inline'
-- Configuring with CXX flag '-fno-inline'
-- Performing Test HAVE_FLAG_Og
-- Performing Test HAVE_FLAG_Og - Success
-- Configuring with C flag '-Og'
-- Configuring with CXX flag '-Og'
-- Performing Test HAVE_FLAG_Wall
-- Performing Test HAVE_FLAG_Wall - Success
-- Configuring with C flag '-Wall'
-- Configuring with CXX flag '-Wall'
-- Performing Test HAVE_FLAG_Wno_unused_private_field
-- Performing Test HAVE_FLAG_Wno_unused_private_field - Success
-- Configuring with C flag '-Wno-unused-private-field'
-- Configuring with CXX flag '-Wno-unused-private-field'
-- Performing Test HAVE_FLAG_fexceptions
-- Performing Test HAVE_FLAG_fexceptions - Success
-- Configuring with C flag '-fexceptions'
-- Performing Test HAVE_FLAG_Wsuggest_override
-- Performing Test HAVE_FLAG_Wsuggest_override - Failed
-- Performing Test HAVE_FLAG_Wnon_virtual_dtor
-- Performing Test HAVE_FLAG_Wnon_virtual_dtor - Success
-- Configuring with CXX flag '-Wnon-virtual-dtor'
-- Performing Test HAVE_FLAG_Wimplicit_fallthrough
-- Performing Test HAVE_FLAG_Wimplicit_fallthrough - Success
-- Configuring with C flag '-Wimplicit-fallthrough'
-- Configuring with CXX flag '-Wimplicit-fallthrough'
-- Performing Test HAVE_FLAG_Wshadow
-- Performing Test HAVE_FLAG_Wshadow - Success
-- Configuring with C flag '-Wshadow'
-- Configuring with CXX flag '-Wshadow'
-- Performing Test HAVE_FLAG_Wno_class_memaccess
-- Performing Test HAVE_FLAG_Wno_class_memaccess - Failed
-- Using GNU gold linker.
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 
-- Found GMP: /usr/include/x86_64-linux-gnu  
-- Found GMP libs: /usr/lib/x86_64-linux-gnu/libgmp.so
-- Performing Test HAVE_FLAG_ggdb3
-- Performing Test HAVE_FLAG_ggdb3 - Success
-- Configuring with C flag '-ggdb3'
-- Configuring with CXX flag '-ggdb3'
-- Performing Test CVC4_NEED_INT64_T_OVERLOADS
-- Performing Test CVC4_NEED_INT64_T_OVERLOADS - Failed
-- Performing Test CVC4_NEED_HASH_UINT64_T_OVERLOAD
-- Performing Test CVC4_NEED_HASH_UINT64_T_OVERLOAD - Failed
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for C++ include ext/stdio_filebuf.h
-- Looking for C++ include ext/stdio_filebuf.h - found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for ffs
-- Looking for ffs - found
-- Looking for optreset
-- Looking for optreset - not found
-- Looking for sigaltstack
-- Looking for sigaltstack - found
-- Looking for strerror_r
-- Looking for strerror_r - found
-- Looking for strtok_r
-- Looking for strtok_r - found
-- Looking for setitimer
-- Looking for setitimer - found
-- Performing Test STRERROR_R_CHAR_P
-- Performing Test STRERROR_R_CHAR_P - Failed
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Looking for antlr3FileStreamNew
-- Looking for antlr3FileStreamNew - found
-- Found ANTLR: /home/makai/repos/forks/CVC4/deps/install/bin/antlr3  
-- Found ANTLR libs: /home/makai/repos/forks/CVC4/deps/install/lib/libantlr3c.a
-- Found Java: /usr/bin/java (found version "11.0.10") found components:  Runtime 
-- Found GTest: /usr/local/lib/libgtest.a  
-- Performing Test HAVE_FLAGWno_unused_comparison
-- Performing Test HAVE_FLAGWno_unused_comparison - Success
CVC4 1.9-prerelease

Build profile             : debug

GPL                       : off
Best configuration        : off

Assertions                : on
Debug symbols             : on
Debug context mem mgr     : off

Dumping                   : on
Muzzle                    : off
Proofs                    : on
Statistics                : on
Tracing                   : on

ASan                      : off
UBSan                     : off
TSan                      : off
Coverage (gcov)           : off
Profiling (gprof)         : off
Unit tests                : on
Valgrind                  : off

Shared libs               : on
Static binary             : off
Python bindings           : off
Java bindings             : off
Python2                   : off

ABC                       : off
CaDiCaL                   : off
CryptoMiniSat             : off
drat2er                   : off
GLPK                      : off
Kissat                    : off
LFSC                      : off
LibPoly                   : off

Build libcvc4 only        : off
MP library                : gmp
Editline                  : off
SymFPU                    : off


CPPLAGS (-D...)           : CVC4_DEBUG CVC4_ASSERTIONS CVC4_DUMPING CVC4_PROOF CVC4_TRACING CVC4_STATISTICS_ON
CXXFLAGS                  : -fno-inline -Og -Wall -Wno-unused-private-field -Wnon-virtual-dtor -Wimplicit-fallthrough -Wshadow -ggdb3
CFLAGS                    : -fno-inline -Og -Wall -Wno-unused-private-field -fexceptions -Wimplicit-fallthrough -Wshadow -ggdb3
Linker flags              :  -fuse-ld=gold

Install prefix            : /usr/local

CVC4 license              : modified BSD

Note that this configuration is NOT built against any GPL'ed libraries, so
it is covered by the (modified) BSD license.  This is, however, not the best
performing configuration of CVC4.  To build against GPL'ed libraries which
improve CVC4's performance, re-configure with '-DENABLE_GPL -DENABLE_BEST'.

Now change to 'build' and type 'make', followed by 'make check' or 'make install'.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/makai/repos/forks/CVC4/build
```

### PR DESCRIPTION
**Pull request by mpreiner**
This commit makes toCNF() iterative to avoid this issue.
Note that the order in which nodes are visited and thus SatLiterals are
created remains the same.

Fixes #6111

### CODE REVIEW

File: test/api/issue6111.cpp [hunk 1]
```diff
@@ -0,0 +1,43 @@
+#include <iostream>
```
Comment (4tXJ7f) [inline test/api/issue6111.cpp:1]: Include boilerplate.

File: src/prop/cnf_stream.cpp [hunk 2]
```diff
@@ -485,47 +468,93 @@ SatLiteral CnfStream::handleIte(TNode iteNode)
...
+        handleAnd(cur);
+      }
+      else if (k == kind::EQUAL && cur[0].getType().isBoolean())
+      {
+        handleIff(cur);
+      }
+      else
+      {
+        convertAtom(cur);
+      }
```
Comment (4tXJ7f) [inline src/prop/cnf_stream.cpp:549]: Nit: may be nicer to use a `switch` statement and just handling the `EQUAL` case in the `default` case. Personal preference, though.

File: src/prop/cnf_stream.cpp [hunk 3]
```diff
@@ -485,47 +468,93 @@ SatLiteral CnfStream::handleIte(TNode iteNode)
...
+
+    if (hasLiteral(cur))
     {
-      nodeLit = convertAtom(node);
+      visit.pop_back();
+      continue;
     }
-    break;
+
+    auto it = cache.find(cur);
```
Comment (4tXJ7f) [inline src/prop/cnf_stream.cpp:495]:
```suggestion
    const auto& it = cache.find(cur);
```

File: src/prop/cnf_stream.cpp [hunk 4]
```diff
@@ -485,47 +468,93 @@ SatLiteral CnfStream::handleIte(TNode iteNode)
...
+      // Only traverse Boolean nodes
+      if (k == kind::NOT || k == kind::XOR || k == kind::ITE
+          || k == kind::IMPLIES || k == kind::OR || k == kind::AND
+          || (k == kind::EQUAL && cur[0].getType().isBoolean()))
+      {
+        // Preserve the order of the recursive version
+        for (size_t i = 0, size = cur.getNumChildren(); i < size; ++i)
+        {
+          visit.push_back(cur[size - 1 - i]);
+        }
```
Comment (4tXJ7f) [inline src/prop/cnf_stream.cpp:509]:
```suggestion
        // Preserve the order of the recursive version
        visit.insert(visit.end(), std::make_reverse_iterator(cur.end()), std::make_reverse_iterator(cur.begin()));      
```
(untested)

File: src/prop/cnf_stream.cpp [hunk 5]
```diff
@@ -363,21 +355,18 @@ SatLiteral CnfStream::handleAnd(TNode andNode)
...
-
   // Get the literal for this node
   SatLiteral andLit = newLiteral(andNode);
 
-  // lit -> (a_1 & a_2 & a_3 & ... & a_n)
-  // ~lit | (a_1 & a_2 & a_3 & ... & a_n)
-  // (~lit | a_1) & (~lit | a_2) & ... & (~lit | a_n)
-  for(unsigned i = 0; i < n_children; ++i) {
+  // Transform all the children first (remembering the negation)
+  SatClause clause(n_children + 1);
```
Comment (4tXJ7f) [inline src/prop/cnf_stream.cpp:362]: Since we are changing this code anyway, could we change the type of `n_children` to `size_t` and maybe change the name to camelCase (same for `n_children` above)?

**Review by 4tXJ7f — CHANGES_REQUESTED** [review]
Great :) Been on my wishlist for a long time. Just some missing boilerplate and some suggestions (feel free to ignore).

File: src/prop/cnf_stream.cpp (hunk 4 above)
Comment (mpreiner) [reply src/prop/cnf_stream.cpp:509]: Unfortunately doesn't work with the current `NodeValue::iterator`

```
In file included from /usr/include/c++/11.1.0/bits/stl_algobase.h:67,                                                                                          
                 from /usr/include/c++/11.1.0/bits/char_traits.h:39,                                                                                           
                 from /usr/include/c++/11.1.0/ios:40,                         
                 from /usr/include/c++/11.1.0/ostream:38,                                                                                                      
                 from /home/ma/git/cvc5-fork/src/./base/check.h:37,                                                                                            
                 from /home/ma/git/cvc5-fork/src/./context/cdhashset.h:21,                                                                                     
                 from /home/ma/git/cvc5-fork/src/./prop/cnf_stream.h:29,                                                                                       
                 from /home/ma/git/cvc5-fork/src/prop/cnf_stream.cpp:16:                                                                                       
/usr/include/c++/11.1.0/bits/stl_iterator.h: In instantiation of ‘constexpr std::reverse_iterator<_Iterator>::reference std::reverse_iterator<_Iterator>::operator*() const [with _Iterator = cvc5::expr::NodeValue::iterator<cvc5::NodeTemplate<false> >; std::reverse_iterator<_Iterator>::reference = cvc5::NodeTemplate<false>&]’:                                                                                                                                                        
/usr/include/c++/11.1.0/bits/stl_uninitialized.h:92:45:   required from ‘static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::reverse_iterator<cvc5::expr::NodeValue::iterator<cvc5::NodeTemplate<false> > >; _ForwardIterator = cvc5::NodeTemplate<false>*; bool _TrivialValueTypes = false]’                                                                                  
/usr/include/c++/11.1.0/bits/stl_uninitialized.h:151:15:   required from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::reverse_iterator<cvc5::expr::NodeValue::iterator<cvc5::NodeTemplate<false> > >; _ForwardIterator = cvc5::NodeTemplate<false>*]’                                                                                                                                                              
/usr/include/c++/11.1.0/bits/stl_uninitialized.h:333:37:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = std::reverse_iterator<cvc5::expr::NodeValue::iterator<cvc5::NodeTemplate<false> > >; _ForwardIterator = cvc5::NodeTemplate<false>*; _Tp = cvc5::NodeTemplate<false>]’                                                                                                   
/usr/include/c++/11.1.0/bits/vector.tcc:751:34:   required from ‘void std::vector<_Tp, _Alloc>::_M_range_insert(std::vector<_Tp, _Alloc>::iterator, _ForwardIterator, _ForwardIterator, std::forward_iterator_tag) [with _ForwardIterator = std::reverse_iterator<cvc5::expr::NodeValue::iterator<cvc5::NodeTemplate<false> > >; _Tp = cvc5::NodeTemplate<false>; _Alloc = std::allocator<cvc5::NodeTemplate<false> >; std::vector<_Tp, _Alloc>::iterator = std::vector<cvc5::NodeTemplate<false> >::iterator]’
/usr/include/c++/11.1.0/bits/stl_vector.h:1665:19:   required from ‘void std::vector<_Tp, _Alloc>::_M_insert_dispatch(std::vector<_Tp, _Alloc>::iterator, _InputIterator, _InputIterator, std::__false_type) [with _InputIterator = std::reverse_iterator<cvc5::expr::NodeValue::iterator<cvc5::NodeTemplate<false> > >; _Tp = cvc5::NodeTemplate<false>; _Alloc = std::allocator<cvc5::NodeTemplate<false> >; std::vector<_Tp, _Alloc>::iterator = std::vector<cvc5::NodeTemplate<false> >::iterator]’
/usr/include/c++/11.1.0/bits/stl_vector.h:1383:22:   required from ‘std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::insert(std::vector<_Tp, _Alloc>::const_iterator, _InputIterator, _InputIterator) [with _InputIterator = std::reverse_iterator<cvc5::expr::NodeValue::iterator<cvc5::NodeTemplate<false> > >; <
template-parameter-2-2> = void; _Tp = cvc5::NodeTemplate<false>; _Alloc = std::allocator<cvc5::NodeTemplate<false> >; std::vector<_Tp, _Alloc>::iterator = std::vector<cvc5::NodeTemplate<false> >::iterator; std::vector<_Tp, _Alloc>::const_iterator = std::vector<cvc5::NodeTemplate<false> >::const_iterator]’
/home/ma/git/cvc5-fork/src/prop/cnf_stream.cpp:506:21:   required from here                                                                                    
/usr/include/c++/11.1.0/bits/stl_iterator.h:241:19: error: cannot bind non-const lvalue reference of type ‘std::reverse_iterator<cvc5::expr::NodeValue::iterator<cvc5::NodeTemplate<false> > >::reference’ {aka ‘cvc5::NodeTemplate<false>&’} to an rvalue of type ‘cvc5::NodeTemplate<false>’
  241 |         return *--__tmp;                                                                                                                               
      |                   ^~~~~                                                                                                                                
cc1plus: note: unrecognized command-line option ‘-Wno-unused-private-field’ may have been intended to silence earlier diagnostics                              
make[2]: *** [src/CMakeFiles/cvc5.dir/build.make:1294: src/CMakeFiles/cvc5.dir/prop/cnf_stream.cpp.o] Error 1
```
I don't think that I want to change that in this PR.

**Review by 4tXJ7f — APPROVED** [review]
LGTM, thanks for the updates.

**Comment by mpreiner** [comment]
Marking do-not-merge until @HanielB had a look.

**Review by HanielB — APPROVED** [review]
LGTM
