### PR TITLE
Simplify and fix how purified terms are managed in the trancendental solver

### LINKED ISSUE #8160: Invalid model on transcendental formula
Hi, 
For this instance, cvc5https://github.com/cvc5/cvc5/commit/e06dd209a23e4667b5e5202d48d7706f0942bca4 gives an invalid model.
```
$ cvc5 delta.smt2 --check-models
Fatal failure within void cvc5::smt::CheckModels::checkModel(cvc5::theory::TheoryModel*, const cvc5::context::CDList<cvc5::NodeTemplate<true> >&, bool) at /root/cvc5/src/smt/check_models.cpp:127
Internal error detected SolverEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     (forall ((V Real)) (and (= 0 (b 0 0)) (forall ((V Real)) (= 0.0 (sin v))) (exists ((V Real)) (= 1.0 (* a a)))))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
Aborted (core dumped)
$ cat delta.smt2
(set-logic ALL)
(declare-fun b (Int Int) Int)
(declare-fun v () Real)
(declare-fun a () Real)
(assert (forall ((V Real)) (and (= 0 (b 0 0)) (forall ((V Real)) (= 0.0 (sin v))) (exists ((V Real)) (= 1.0 (* a a))))))
(check-sat)
```

### PR DESCRIPTION
**Pull request by ajreynol**
Simplification is leftover from the sine symmetry heuristic, now the mapping from terms to what purifies them is injective.
Also makes the mapping context-dependent.

It also ensures that we keep model values for purification arguments. Fixes #8160.

### CODE REVIEW

File: src/theory/arith/nl/transcendental/transcendental_state.cpp [hunk 1]
```diff
@@ -106,13 +112,13 @@ void TranscendentalState::init(const std::vector<Node>& xts,
...
-        needsMaster.push_back(a);
+        // must assign a purified term
+        needsPurify.push_back(a);
       }
       else
       {
-        d_trMaster[a] = a;
-        d_trSlaves[a].insert(a);
+        // assume own purified
+        d_trPurify[a] = a;
```
Comment (nafur) [inline src/theory/arith/nl/transcendental/transcendental_state.cpp:121]: Also update `d_trPurifies`?

File: src/theory/arith/nl/transcendental/transcendental_state.cpp [hunk 2]
```diff
@@ -431,6 +437,16 @@ void TranscendentalState::doSecantLemmas(const std::pair<Node, Node>& bounds,
   }
 }
 
+bool TranscendentalState::isPurified(TNode n) const
+{
+  NodeMap::const_iterator it = d_trPurify.find(n);
```
Comment (nafur) [inline src/theory/arith/nl/transcendental/transcendental_state.cpp:442]: Couldn't we simply check whether `n` is in `d_trPurifies`?

File: src/theory/arith/nl/transcendental/transcendental_solver.cpp [hunk 3]
```diff
@@ -115,6 +115,7 @@ bool TranscendentalSolver::preprocessAssertionsCheckModel(
   // get model bounds for all transcendental functions
   Trace("nl-ext-cm") << "----- Get bounds for transcendental functions..."
                      << std::endl;
+  context::CDHashMap<Node, Node>::const_iterator itp;
```
Comment (nafur) [inline src/theory/arith/nl/transcendental/transcendental_solver.cpp:118]: I'd prefer to declare a variable where it is used.

File: src/theory/arith/nl/transcendental/transcendental_state.h [hunk 4]
```diff
@@ -181,18 +191,21 @@ struct TranscendentalState : protected EnvObj
...
    *
    * This is used for ensuring that the argument y of SINE we process is on
    * the interval [-pi .. pi], and that exponentials are not applied to
    * arguments that contain transcendental functions.
    */
-  std::map<Node, Node> d_trMaster;
-  std::map<Node, std::unordered_set<Node>> d_trSlaves;
+  NodeMap d_trPurify;
+  /** inverse mapping of above */
+  NodeMap d_trPurifies;
```
Comment (nafur) [inline src/theory/arith/nl/transcendental/transcendental_state.h:206]: A general question about these that is not totally clear to me from the code: Do these maps (conceptually) have a one-to-one relationship? In particular: can it every happen that two nodes are purified to the same purification term? (I don't think so, but not entirely sure).
If this is the case, please make this explicit by asserting that the purification term is indeed new when inserting stuff in `initLastCall()`.

**Review by nafur — APPROVED** [review]
LGTM.
