### PR TITLE
Move public headers into top-level include directory.

### LINKED ISSUE #9553: Script fix-install-header.sh does not work properly on MacOS
**Describe the bug**

The script `fix-install-header.sh` uses the 'sed' options `-i'' `, which do not work on Mac OS.
On Linux, this modifies `*.h` files in place. 

On MacOS, the syntax is `-i <extension>`  so this command creates a backup with suffix 'h-e' for every '.h' file.
Because the `find` applies sed to every file in the install `include` directory, the whole thing results in this:
```
> ls /usr/local/include/cvc5
cvc5.h                  cvc5_export.h           cvc5_kind.h             cvc5_sort_kind.h        cvc5_types.h
cvc5.h-e                cvc5_export.h-e         cvc5_kind.h-e           cvc5_sort_kind.h-e      cvc5_types.h-e
cvc5.h-e-e              cvc5_export.h-e-e       cvc5_kind.h-e-e         cvc5_sort_kind.h-e-e    cvc5_types.h-e-e
```

Things get worse if you install a new version as the sed command will create `.h-e-e-e-e-e` files and more every time.

### LINKED ISSUE #9556: Missing CVC5_EXPORTs cause linking failure
**Describe the bug**

Three methods in `src/api/cpp/cvc5_types.h` are missing the 'CVC5_EXPORT' annotation:
```
std::ostream& operator<<(std::ostream& out, BlockModelsMode bmode);
std::ostream& operator<<(std::ostream& out, LearnedLitType ltype);
std::ostream& operator<<(std::ostream& out, ProofComponent pc);
```

This causes an obscure link error when trying to link `libcvc5` with say `murxla`
```
Undefined symbols for architecture arm64:
  "cvc5::modes::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, cvc5::modes::BlockModelsMode)", referenced from:
      murxla::Tracer<murxla::cvc5::Cvc5TracerData>& murxla::operator<<<murxla::cvc5::Cvc5TracerData, cvc5::modes::BlockModelsMode>(murxla::Tracer<murxla::cvc5::Cvc5TracerData>&, cvc5::modes::BlockModelsMode) in cvc5_solver.cpp.o
```

### PR DESCRIPTION
**Pull request by mpreiner**
This PR moves the public API headers into a top-level include directory. This makes it easier to find the public API of cvc5 and makes the install headers script obsolete.

Fixes #9553
Fixes #9556

### CODE REVIEW

File: include/cvc5/cvc5.h [hunk 1]
```diff
@@ -4373,8 +4376,7 @@ class CVC5_EXPORT Solver
    * for showing the satisfiability of the last call to checkSat using the
    * current model. This method will only return false (for any `v`) if
    * option
-   * \verbatim embed:rst:inline :ref:`model-cores <lbl-option-model-cores>`\endverbatim
-   * has been set.
+   * \verbatim embed:rst:inline :ref:`model-cores <lbl-option-model-cores>`\endverbatim has been set.
```
Comment (aniemetz) [inline include/cvc5/cvc5.h:4379]: This looks longer than 80 char.

**Review by aniemetz — APPROVED** [review]
One minor thing, else LGTM.

File: include/cvc5/cvc5.h (hunk 1 above)
Comment (mpreiner) [reply include/cvc5/cvc5.h]: Looks like I missed reverting the formatting here. I actually didn't intend to change any of the formatting of the text.
