### PR TITLE
Fix issue related to sanity checking integer models

### LINKED ISSUE #6774: (default) Invalid model for ALIRA formula
~~~~
(set-logic ALIRA)
(declare-const x Real)
(declare-fun i () Int)
(declare-fun i1 () Int)
(push)
(assert (< 1 (- i)))
(check-sat)
(pop)
(push)
(assert (or (>= i1 (* 5 (- i)))))
(check-sat)
(pop)
(assert (or (> i1 1) (= x (to_real i))))
(check-sat)
(assert (not (is_int x)))
(check-sat)
~~~~
~~~~
sat
sat
sat
Fatal failure within void cvc5::smt::CheckModels::checkModel(cvc5::smt::Model*, cvc5::context::CDList<cvc5::NodeTemplate<true> >*, bool) at /home/cvc5/src/smt/check_models.cpp:125
Internal error detectedSmtEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     (not (is_int x))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
Aborted (core dumped)
~~~~

### PR DESCRIPTION
**Pull request by ajreynol**
We now insist that we sanity check integer models in linear logics.  Previously, we could trigger an assertion failure in Minisat if a user asked for a model in a state where the linear solver had assigned a real value to an integer variable, as we would be sending a lemma during collectModelValues in a state where we had already terminated with "sat".

This also changes an assertion to warning, to allow the regression to pass.

Fixes #6774 (This PR fixes a followup issue after the original bad model reported there was fixed by sanity checks).

As the assertion failure is downgraded to a warning, fixes https://github.com/cvc5/cvc5/issues/6988, fixes https://github.com/cvc5/cvc5/issues/7252.

### CODE REVIEW

**Comment by ajreynol** [comment]
No, since we still are delaying this check until model construction time if we need a last call effort check.

On second thought, we could either guard it by only running it if we haven't already (e.g. if needs last call effort is true).  Alternatively, we could have the policy that we always sanity check at full effort.

What do you think?

**Comment by ajreynol** [comment]
Yeah, I do too, I'll change.

File: src/theory/arith/theory_arith.cpp [hunk 1]
```diff
@@ -383,9 +386,9 @@ bool TheoryArith::sanityCheckIntegerModel()
       Trace("arith-check") << p.first << " -> " << p.second << std::endl;
       if (p.first.getType().isInteger() && !p.second.getType().isInteger())
       {
-        Assert(false) << "TheoryArithPrivate generated a bad model value for "
-                        "integer variable "
-                      << p.first << " : " << p.second;
+        Warning() << "TheoryArithPrivate generated a bad model value for "
+                     "integer variable "
+                  << p.first << " : " << p.second;
```
Comment (nafur) [inline src/theory/arith/theory_arith.cpp:391]: Why is this only a warning now?

**Review by nafur — APPROVED** [review]
