### PR TITLE
Fix `str.replace_re` and `str.replace_re_all`

### LINKED ISSUE #6057: (no-strings-lazy-pp) Invalid model  (replace_re_all)
Commit: 8562fbeb

```
$cvc4 --no-strings-lazy-pp --check-models --produce-models --strings-exp -q bug.smt2
Fatal failure within void CVC4::smt::CheckModels::checkModel(CVC4::smt::Model*, CVC4::context::CDList<CVC4::NodeTemplate<true> >*, bool) at src/smt/check_models.cpp:131
Internal error detectedSmtEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     (let ((_let_1 (re.* re.allchar ))) (let ((_let_2 (re.++ _let_1 (re.++ (str.to_re "/evil") _let_1)))) (let ((_let_3 (str.replace_re "/evil" _let_2 literal_0))) (let ((_let_4 (str.<= (str.++ literal_0 "/question/type/numerical/editquestion.html") (str.replace_re_all _let_3 _let_2 _let_3)))) (and _let_4 _let_4)))))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
[1]    15440 abort      cvc4 --no-strings-lazy-pp --check-models --produce-models --strings-exp -q 
$cat bug.smt2 
(declare-fun literal_0 () String)
(assert (and (str.<= (str.++ literal_0 "\u{2f}\u{71}\u{75}\u{65}\u{73}\u{74}\u{69}\u{6f}\u{6e}\u{2f}\u{74}\u{79}\u{70}\u{65}\u{2f}\u{6e}\u{75}\u{6d}\u{65}\u{72}\u{69}\u{63}\u{61}\u{6c}\u{2f}\u{65}\u{64}\u{69}\u{74}\u{71}\u{75}\u{65}\u{73}\u{74}\u{69}\u{6f}\u{6e}\u{2e}\u{68}\u{74}\u{6d}\u{6c}") 
(str.replace_re_all (str.replace_re "\u{2f}\u{65}\u{76}\u{69}\u{6c}" (re.++ (re.* re.allchar) (re.++ (str.to_re "\u{2f}\u{65}\u{76}\u{69}\u{6c}") (re.* re.allchar))) literal_0) (re.++ (re.* re.allchar) (re.++ (str.to_re "\u{2f}\u{65}\u{76}\u{69}\u{6c}") (re.* re.allchar))) (str.replace_re "\u{2f}\u{65}\u{76}\u{69}\u{6c}" (re.++ (re.* re.allchar) (re.++ (str.to_re "\u{2f}\u{65}\u{76}\u{69}\u{6c}") (re.* re.allchar))) literal_0))) 
(str.<= (str.++ literal_0 "\u{2f}\u{71}\u{75}\u{65}\u{73}\u{74}\u{69}\u{6f}\u{6e}\u{2f}\u{74}\u{79}\u{70}\u{65}\u{2f}\u{6e}\u{75}\u{6d}\u{65}\u{72}\u{69}\u{63}\u{61}\u{6c}\u{2f}\u{65}\u{64}\u{69}\u{74}\u{71}\u{75}\u{65}\u{73}\u{74}\u{69}\u{6f}\u{6e}\u{2e}\u{68}\u{74}\u{6d}\u{6c}") (str.replace_re_all (str.replace_re "\u{2f}\u{65}\u{76}\u{69}\u{6c}" (re.++ (re.* re.allchar) (re.++ (str.to_re "\u{2f}\u{65}\u{76}\u{69}\u{6c}") (re.* re.allchar))) literal_0) (re.++ (re.* re.allchar) (re.++ (str.to_re "\u{2f}\u{65}\u{76}\u{69}\u{6c}") (re.* re.allchar))) (str.replace_re "\u{2f}\u{65}\u{76}\u{69}\u{6c}" (re.++ (re.* re.allchar) (re.++ (str.to_re "\u{2f}\u{65}\u{76}\u{69}\u{6c}") (re.* re.allchar))) literal_0)))))
(assert (not (str.<= "\u{2f}\u{71}\u{75}\u{65}\u{73}\u{74}\u{69}\u{6f}\u{6e}\u{2f}\u{74}\u{79}\u{70}\u{65}\u{2f}\u{6e}\u{75}\u{6d}\u{65}\u{72}\u{69}\u{63}\u{61}\u{6c}\u{2f}\u{65}\u{64}\u{69}\u{74}\u{71}\u{75}\u{65}\u{73}\u{74}\u{69}\u{6f}\u{6e}\u{2e}\u{68}\u{74}\u{6d}\u{6c}" "\u{2f}\u{65}\u{76}\u{69}\u{6c}")))
(check-sat)
(exit)
```

### PR DESCRIPTION
**Pull request by 4tXJ7f**
Fixes #6057. The reductions of `str.replace_re` and `str.replace_re_all`
were not correctly enforcing that the operations replace the _first_
occurrence of some regular expression in a string. This commit fixes the
issue by introducing a new operator `str.indexof_re(s, r, n)`, which,
analoguously to `str.indexof`, returns the index of the first match of
the regular expression `r` in `s`. The commit adds basic rewrites for
evaluating the operator as well as its reduction. Additionally, it
converts the reductions of `str.replace_re` and `str.replace_re_all` to
use that new operator. This simplifies the reductions of the two
operators and ensures that the semantics are consistent between the two.

### CODE REVIEW

**Comment by ajreynol** [comment]
Are https://github.com/cvc5/cvc5/issues/6337 or the 6th benchmark on https://github.com/cvc5/cvc5/issues/6203 fixed as well?

File: src/theory/strings/theory_strings_preprocess.cpp [hunk 1]
```diff
@@ -251,6 +251,92 @@ Node StringsPreprocess::reduce(Node t,
...
+    Node k1 =
+        sc->mkSkolemCached(rem, r, SkolemCache::SK_FIRST_MATCH_PRE, "iorpre");
+    Node k2 = sc->mkSkolemCached(rem, r, SkolemCache::SK_FIRST_MATCH, "iorm");
+    Node k3 =
+        sc->mkSkolemCached(rem, r, SkolemCache::SK_FIRST_MATCH_POST, "iorpost");
+
+    Node sigma = nm->mkNode(REGEXP_SIGMA);
+    Node sigmaStar = nm->mkNode(REGEXP_STAR, sigma);
+    Node anyMatchRe = nm->mkNode(REGEXP_CONCAT, sigmaStar, r, sigmaStar);
+    // ~in_re(rem, _* ++ r ++ _*)
```
Comment (ajreynol) [inline src/theory/strings/theory_strings_preprocess.cpp:277]: I don't think the reduction requires use of `_*`.  Doesnt the use of substr suffice?

**Review by ajreynol — CHANGES_REQUESTED** [review]
I have one initial question about the reduction which seems like it could be simplified.

File: src/theory/strings/theory_strings_preprocess.cpp (hunk 1 above)
Comment (4tXJ7f) [reply src/theory/strings/theory_strings_preprocess.cpp:277]: The problem is that we want to say that there is no match of `r` in `s`. For example, consider `str.indexof("abc", str.to_re("b"), 0)`. We want to check whether there is any match of the regular expression `str.to_re("b")` in `"abc"`. To do that, we check whether `"abc"` matches `re.++(_*, str.to_re("b"), _*)`

**Comment by 4tXJ7f** [comment]
> Are #6337 or the 6th benchmark on #6203 fixed as well?

Sorry, I missed those. Yes, it fixes benchmark 6 from #6337 and the first two benchmarks from #6203. The third benchmark seems to time out and the last one is unrelated to `replace_re`/`replace_re_all`.

File: src/theory/strings/theory_strings_preprocess.cpp (hunk 1 above)
Comment (ajreynol) [reply src/theory/strings/theory_strings_preprocess.cpp:277]: There should be a better way to do this.  My concern here is that this condition is similar to the part that says there are no matches before the return index.

The idea would be that there is a quantified formula that says "there are no matches before k", where `k` is either 0 if `n` is out of bounds, `skk` if `skk` is not -1, and `len(s)` otherwise.

**Review by ajreynol — CHANGES_REQUESTED** [review]

File: src/theory/strings/theory_strings_preprocess.cpp [hunk 2]
```diff
@@ -251,6 +251,92 @@ Node StringsPreprocess::reduce(Node t,
...
+    // in_re(k2, r)
+    Node match = nm->mkNode(STRING_IN_REGEXP, k2, r);
+    // skk = n + len(sk1)
+    Node ret = skk.eqNode(nm->mkNode(PLUS, n, nm->mkNode(STRING_LENGTH, k1)));
+    Node retMatch = nm->mkNode(AND, {split, firstMatch, match, ret});
+
+    // assert:
+    // IF:   ~in_re(rem, _* ++ r ++ _*) OR n > len(s) OR 0 > n
+    // THEN: skk = -1
+    // ELIF: in_re("", r)
```
[the remark this answers is not in the document]
Comment (4tXJ7f) [reply src/theory/strings/theory_strings_preprocess.cpp:320]: It does (see comment above).

File: src/theory/strings/theory_strings_preprocess.cpp [hunk 3]
```diff
@@ -696,70 +772,87 @@ Node StringsPreprocess::reduce(Node t,
...
 
-    // IF in_re(x, re.++(_*, y', _*))
-    // THEN:
+    // IF indexof(x, y', 0) = -1
+    // THEN: k = x
+    // ELSE:
     //   numOcc > 0 ^
     //   k = Us(0) ^ Us(numOcc) = substr(x, Uf(numOcc)) ^
-    //   Uf(0) = 0 ^ not(in_re(substr(x, Uf(numOcc)), re.++(_*, y', _*)))
+    //   Uf(0) = 0 ^ indexof(substr(x, Uf(numOcc)), y', 0) = -1 ^
```
Comment (ajreynol) [inline src/theory/strings/theory_strings_preprocess.cpp:829]:
```suggestion
    //   Uf(0) = 0 ^ indexof_re(substr(x, Uf(numOcc)), y', 0) = -1 ^
```

File: src/theory/strings/theory_strings_preprocess.cpp [hunk 4]
```diff
@@ -696,70 +772,87 @@ Node StringsPreprocess::reduce(Node t,
...
     // the remainder after processing the i^th occurrence of y in x.
+    //
+    // Visualization of Uf(i) and Ul(i):
+    //
+    // x = |------------| match 1 |-----------| match 2   |---|
+    //     |                      |                       |
+    //     Uf(0)                  Uf(1)                   Uf(2)
+    //
+    //                  |---------|           |-----------|
+    //                    Ul(1)                 Ul(2)
```
Comment (ajreynol) [inline src/theory/strings/theory_strings_preprocess.cpp:853]: Should Ul be aligned at the beginning of these?

File: src/theory/strings/theory_strings_preprocess.cpp [hunk 5]
```diff
@@ -618,42 +698,41 @@ Node StringsPreprocess::reduce(Node t,
...
-    // ELSE: k = x
-    asserts.push_back(nm->mkNode(
-        ITE,
-        hasMatch,
+    // IF: indexof_re(x, y, 0) = -1
+    // THEN: k = x
+    // ELSE:
+    //   x = k1 ++ k2 ++ k3 ^
+    //   len(k1) = indexof_re(x, y, 0) ^
+    //   (forall l. 0 < l < len(k2) => ~in_re(substr(k2, 0, l), r)) ^
```
Comment (ajreynol) [inline src/theory/strings/theory_strings_preprocess.cpp:728]: Should this be `0 <= l < len(k2)` ?  The comment matches what is implemented, but I'm wondering if this is correct.

File: src/theory/strings/theory_strings_preprocess.cpp [hunk 6]
```diff
@@ -696,70 +772,87 @@ Node StringsPreprocess::reduce(Node t,
     lemmas.push_back(k.eqNode(nm->mkNode(APPLY_UF, us, zero)));
     // Us(numOcc) = substr(x, Uf(numOcc))
     lemmas.push_back(usno.eqNode(rem));
-    // Uf(0) = 0
+    // Uf(-1) = 0
```
Comment (ajreynol) [inline src/theory/strings/theory_strings_preprocess.cpp:775]: This isn't accurate, right?

**Review by ajreynol — CHANGES_REQUESTED** [review]

File: src/theory/strings/theory_strings_preprocess.cpp (hunk 4 above)
Comment (4tXJ7f) [reply src/theory/strings/theory_strings_preprocess.cpp:853]: `Ul(i)` is the length, which is why I put it in the middle. I agree that it is a bit hard to see that this is a length and not an index. Let me know if you have a better idea.

File: src/theory/strings/theory_strings_preprocess.cpp (hunk 5 above)
Comment (4tXJ7f) [reply src/theory/strings/theory_strings_preprocess.cpp:728]: Ah, the comment is missing a crucial part of the implementation:
```
len(k2) = 0 v forall l. 0 < l < len(k2) => ~in_re(substr(k2, 0, l), r)
```

I think that we can just write `forall l. 0 <= l < len(k2) => ~in_re(substr(k2, 0, l), r)`, though, because of the strict upper bound.

**Review by ajreynol — APPROVED** [review]
LGTM, happy to have this.
