### PR TITLE
[proofs] [sat] Cover missed case when tracking optimized clauses' proofs

### LINKED ISSUE #9669: Segmentation fault on QF_UFLIA instance
Greetings,
For this instance, a crash bug occurred. Sincerely hope that this instance would be helpful for cvc5 team.
(we used ./configure.sh --auto-download --assertions)
```
$ ./cvc5 ./small.smt2 --incremental --check-proofs
sat
sat
sat
cvc5 suffered a segfault.
Offending address is 0x8
Looks like a NULL pointer was dereferenced.
Segmentation fault

$ cat ./small.smt2
(set-logic QF_UFLIA)
(declare-const x1 Bool)
(declare-const x7 Bool)
(declare-const x74 Bool)
(declare-const x4 Bool)
(declare-const x2 Bool)
(declare-const x22 Bool)
(declare-const x24 Bool)
(declare-const x3 Bool)
(declare-fun x (Int) Int)
(assert (and (and true (or x1 (not x74))) (and (or x24 (= (x 3) (x 1))) (and (= 1 (x 0)) (or x22 (= (x 1) (x 0))) (or x22 (not (and x1 x24))) (or x74 (not (and x7 x22))))) (and (or x74 x7) (or (and x1 x24) (= (x 2) (+ 1 (x 3))))) (and (or x74 (= (x 4) (x 2))) (or (not x2) (= (x 4) (+ 1 (x 2))))) (or (not x3) x4)))
(check-sat)
(assert (and x7 (or x2 x4) (= 0 (* 1 (x (- 5 1))))))
(push)
(check-sat)
(check-sat)
(pop)
```
cvc5 version/commit: [c957d0c](https://github.com/cvc5/cvc5/commit/c957d0cb7558a8d136361c4be1dbc9648765b5ed)
Operating system: Ubuntu 20.04

### PR DESCRIPTION
**Pull request by HanielB**
We must only track the clauses, whose levels are optimized, for which we are generating proofs. Since we do not generate proofs for redundant clauses we must avoid tracking in such cases. Previously we were only checking for when the clause already had a generator, but there are other tests in `endResChain`. This commit moves the place where we track to guarantee we only track after all the tests are done.

Fixes #9669

### CODE REVIEW

File: src/prop/sat_proof_manager.h [hunk 1]
```diff
@@ -414,8 +414,11 @@ class SatProofManager : protected EnvObj
    *
    * @param conclusion the node-level conclusion of the resolution chain
    * @param conclusionLits the set of literals in the conclusion
+   * @param clauseLevel the level of the clause in the SAT solver (if any)
    */
-  void endResChain(Node conclusion, const std::set<SatLiteral>& conclusionLits);
+  void endResChain(Node conclusion,
+                   const std::set<SatLiteral>& conclusionLits,
+                   uint32_t clauseLevel = -1);
```
Comment (ajreynol) [inline src/prop/sat_proof_manager.h:421]: Should this be uint with a negative default value?

**Review by ajreynol — CHANGES_REQUESTED** [review]

File: src/prop/sat_proof_manager.h (hunk 1 above)
Comment (HanielB) [reply src/prop/sat_proof_manager.h:421]: It's -1 because it'll become the max which is guaranteed to not trigger the behavior of tracking the clause. I'll clarify in the documentation.

**Review by ajreynol — APPROVED** [review]
