### PR TITLE
Fix for large negative bounds in fmf bounded integers

### LINKED ISSUE #9992: Fatal failure at integer_gmp_imp.cpp:430
Greetings,
For this instance, a crash bug occurred.
(we used ./configure.sh --auto-download --assertions)
```
$ ./cvc5  ./small.smt2
Fatal failure within long int cvc5::internal::Integer::getLong() const at cvc5-d43f1b6/src/util/integer_gmp_imp.cpp:430
Check failure

 __gmpz_fits_slong_p(d_value.get_mpz_t()) != 0
Overflow detected in Integer::getLong().
Aborted

$ cat ./small.smt2
(set-logic QF_SLIA)
(declare-fun s () String)
(assert (ite (str.prefixof "-" (str.substr s 0 (str.indexof_re "9" (re.comp (re.opt (re.comp re.all))) (str.to_int (str.replace_re_all s re.allchar s))))) false (= 1 (str.to_int (str.substr s (+ 1 1 1) 1)))))
(assert (not (= 1 (str.len (str.substr s (+ 1 1 1) (+ 1 1))))))
(check-sat)
```
commit version: [d43f1b6](https://github.com/cvc5/cvc5/commit/d43f1b624a04ef06510125d7e3a43b875bf0317b)
release version: 1.0.7

### PR DESCRIPTION
**Pull request by ajreynol**
Fixes #9992.

### CODE REVIEW

File: src/theory/quantifiers/fmf/bounded_integers.cpp [hunk 1]
```diff
@@ -855,23 +855,34 @@ bool BoundedIntegers::getBoundElements( RepSetIterator * rsi, bool initial, Node
...
         // 9999 is an arbitrary range past which we do not do exhaustive
         // bounded instantation, based on the check below.
-        Node ra = rewrite(
-            nm->mkNode(Kind::LEQ, range, nm->mkConstInt(Rational(9999))));
         Node tl = l;
         Node tu = u;
         getBounds( q, v, rsi, tl, tu );
         Assert(!tl.isNull() && !tu.isNull());
-        if (ra.isConst() && ra.getConst<bool>())
+        if (rat < Rational(9999))
```
Comment (HanielB) [inline src/theory/quantifiers/fmf/bounded_integers.cpp:872]: document why this value

Comment (ajreynol) [reply src/theory/quantifiers/fmf/bounded_integers.cpp:872]: Its documented on line 866.

Comment (HanielB) [reply src/theory/quantifiers/fmf/bounded_integers.cpp:872]: Sorry, missed that

**Review by HanielB — APPROVED** [review]
