### PR TITLE
Improved fix for arith nl comparison proof generator

### LINKED ISSUE #12376: Fatal failure at cvc5/src/theory/arith/nl/ext/arith_nl_compare_proof_gen.cpp:236 with --check-proofs
**Describe the bug**
Running the following SMT-LIB2 example triggers a fatal failure (core dump) in cvc5.
Input:
```smt2
(set-logic NIRA)
(declare-const p Int)
(declare-const p6 Int)
(declare-const p8 Int)
(assert (and (> (to_real p8) 0.0) (< (to_real p8) (to_real 5))))
(assert (= 2 (mod p (+ 1 (abs p6)))))
(assert (= (* 2 p) (to_int (/ (+ (to_real p) (/ (to_real (- p8)) (+ 0.0 (abs (to_real p6))))) 0.00000001))))
(check-sat)
```
Output:
```
cvc5 test.smt2 --check-proofs
Fatal failure within virtual std::shared_ptr<cvc5::internal::ProofNode> cvc5::internal::theory::arith::nl::ArithNlCompareProofGenerator::getProofFor(cvc5::internal::Node) at cvc5/src/theory/arith/nl/ext/arith_nl_compare_proof_gen.cpp:236
Check failure

 false
ArithNlCompareProofGenerator failed explain deq
Aborted (core dumped)
```
Using `(set-logic QF_NIRA)` does not trigger this failure.

**Command line arguments**: `--check-proofs`
**cvc5 version/commit**: `This is cvc5 version 1.3.3.dev+main@ade7f5f9b [git ade7f5f9b on branch main]`.
**Operating system**: `Linux iscas 5.4.0-214-generic #234-Ubuntu SMP Fri Mar 14 23:50:27 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux`.

**`configure.sh` options**  
`./configure.sh production --assertions --auto-download`

**`configure.sh` output**  
```
cvc5 1.3.3.dev

Build profile             : production

Assertions                : on
Debug symbols             : off
Debug context mem mgr     : off

Muzzle                    : off
Statistics                : on
Tracing                   : off

ASan                      : off
UBSan                     : off
TSan                      : off
Coverage (gcov)           : off
Profiling (gprof)         : off
Unit tests                : off
Valgrind                  : off

Shared build              : on
Python bindings           : off
Java bindings             : off
Interprocedural opt.      : off

CryptoMiniSat             : off
GLPK                      : off
Kissat                    : off
LibPoly                   : on (local)
CoCoALib                  : off
MP library                : gmp (system)
Editline                  : off

Api docs                  : off
```

### PR DESCRIPTION
**Pull request by ajreynol**
Fixes #12376

Reverts part of the change on https://github.com/cvc5/cvc5/pull/12277.

### CODE REVIEW

File: src/theory/arith/nl/ext/arith_nl_compare_proof_gen.cpp [hunk 1]
```diff
@@ -233,9 +233,18 @@ std::shared_ptr<ProofNode> ArithNlCompareProofGenerator::getProofFor(Node fact)
           itd = deq.find(etgt);
           if (itd == deq.end())
           {
-            Assert(false) << "ArithNlCompareProofGenerator failed explain deq";
-            expSuccess = false;
-            break;
+            // maybe it was v != 0 when we are looking for to_real(v) != 0.0
+            if (etgt.getKind()==Kind::TO_REAL)
```
Comment (HanielB) [inline src/theory/arith/nl/ext/arith_nl_compare_proof_gen.cpp]: format

File: src/theory/arith/nl/ext/arith_nl_compare_proof_gen.cpp [hunk 2]
```diff
@@ -386,7 +395,7 @@ Node ArithNlCompareProofGenerator::isDisequalZero(const Node& g)
   if (g.getKind() == Kind::NOT && g[0].getKind() == Kind::EQUAL
       && g[0][1].isConst() && g[0][1].getConst<Rational>().isZero())
   {
-    return g[0][0].getKind() == Kind::TO_REAL ? g[0][0][0] : g[0][0];
+    return g[0][0];
```
Comment (HanielB) [inline src/theory/arith/nl/ext/arith_nl_compare_proof_gen.cpp:399]: what is going on with this change? Overall I'm a bit at a loss at what is the expected behavior of these methods with all the potential corner cases...

Comment (ajreynol) [reply src/theory/arith/nl/ext/arith_nl_compare_proof_gen.cpp:399]: This utility method was checking if we are a disequality with zero and returning the term that is disequal to zero, with the previous change this was also stripping off "to_real" automatically, but its clearer to not have the utility do this since it leads to further complications.

Comment (HanielB) [reply src/theory/arith/nl/ext/arith_nl_compare_proof_gen.cpp:399]: I see, thanks! But what I was wondering the most is the expected behavior of `getProofFor`, i.e., when is it expected to succeed. It's not clear to me that it is always...

Comment (ajreynol) [reply src/theory/arith/nl/ext/arith_nl_compare_proof_gen.cpp:399]: It is always expected to work :)
Indeed there are a lot of corner cases which testing is uncovering.

Comment (HanielB) [reply src/theory/arith/nl/ext/arith_nl_compare_proof_gen.cpp:399]: I see. All right!
